In [1]:
import numpy as np
import pandas as pd

/home/chinmay/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/chinmay/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [2]:
a = 5
type(a)

int

In [3]:
a = {4:5}

In [4]:
type(a)

dict

In [5]:
def calc_square(input1=2):
    return input1**2

In [6]:
calc_square(55)

3025

In [7]:
calc_square()

4

In [8]:
class Dog:
    pass


In [9]:
d1 = Dog()

In [10]:
type(d1)

__main__.Dog

In [11]:
d2 = Dog()

In [12]:
id(d1) == id(d2)

False

In [24]:
class Dog:

    # Class Attribute
    species = 'mammal'
    # Initializer / Instance Attributes
    def __init__(self, name, age):
        self
        self.name = name
        self.age = age

In [25]:
d1 = Dog('xyz', 21)
d2 = Dog('abc', 15)

In [26]:
print (d1.species)
print (d1.no_of_eyes)

xyz
2


In [16]:
d1.name

'xyz'

In [17]:
d2.age

15

In [18]:
d2.name

'abc'

In [19]:
d2.species

'mammal'

In [20]:
d1.name

'xyz'

In [ ]:
class Dog:

    # Class Attribute
    species = 'mammal'

    # Initializer / Instance Attributes
    def __init__(self, name, age):
        self.name = name
        self.age = age

    # instance method
    def description(self):
        return "{} is {} years old and is a {}".format(self.name, self.age, self.species)


In [31]:
class Dog:

    # Class Attribute
    species = 'mammal'

    # Initializer / Instance Attributes
    def __init__(self, name, age):
        self.name = name
        self.age = age

In [32]:
d1 = Dog('a',24)
d2 = Dog('b',25)
d3 = Dog('c',26)
d4 = Dog('d',27)

In [33]:
def max_age(*args):
    return max(args)

In [34]:
max_age(d1.age,d2.age,d3.age,d4.age)

27

In [28]:
d1 = Dog('xyz', 21)

In [29]:
d1.name

'xyz'

In [30]:
d1.description()

'xyz is 21 years old and is a mammal'

Create class Person
with class attribute no_of_ears

instance attributes - name and age

p1, p2, p3

create a function outside the class which returns
the maximum age out of the 3 objects


In [42]:
class Email:
    is_sent = False
    def send_email(self):
        self.is_sent = True

In [43]:
e1 = Email()

In [44]:
e1.is_sent

False

In [45]:
e1.send_email()

In [46]:
e1.is_sent

True

In [53]:
class A:
	def hello(self):
		print ("I am in A")


class B(A):
    def hello1(self):
        print ("I am in B")

class C(B):
    def hello2(self):
        print ("I am in C")

In [48]:
a1 = A()

In [54]:
c1 = C()

In [55]:
dir(c1)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'hello',
 'hello1',
 'hello2']

In [49]:
dir(a1)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'hello']

In [52]:
b = B()
dir(b)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'hello']

In [58]:
class A:
	def hello(self):
		print ("I am in A")

class B(A):
    
	def hello(self):
		super(B,self).hello()
		print ("I am in B")


b1 = B()
b1.hello()


I am in A
I am in B


In [70]:
class Parent(object):
    def __init__(self):
        self.value = 5

    def get_value(self):
        return self.value + 10

class Child(Parent):
    def get_value(self):
#         self.value = 0
        print (super(Child,self).get_value())
        return self.value + 1

c = Child()
print (c.get_value())

15
6


In [71]:
l1 = [[2,3,4],[4,5,6]]

In [72]:
np.array(l1)

array([[2, 3, 4],
       [4, 5, 6]])

In [76]:
a = np.arange(0,9).reshape(1,3,3)

In [77]:
a

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [83]:
a = np.arange(0,30)

In [84]:
a1 = a.reshape(2,5,3)

In [85]:
a1

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [87]:
a1.shape

(2, 5, 3)

In [88]:
a1[:,:,0]

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27]])

In [89]:
a1[:,:,1]

array([[ 1,  4,  7, 10, 13],
       [16, 19, 22, 25, 28]])